/* 콘텐츠를 추가할 때 id와 문제 id를 중복 없이 유지하세요.
   answer는 정답 문구입니다. 보기는 실행 중 섞입니다.
   inference는 앞 단계에서 정답을 보여주지 않은 어휘를 사용합니다. */
const HANJA_DATA = [
 {id:'yak',hanja:'約',sound:'약',meaning:'약속할 약',theme:'약속의 정원',icon:'🌿',color:'#e6edce',core:'서로 정하다',description:'시간이나 지켜야 할 일을 서로 정하는 뜻을 찾아봐요.',words:[{word:'약속',hanja:'約束',meaning:'어떤 일을 하기로 서로 정함',example:'친구와 내일 만나기로 약속했어요.'},{word:'예약',hanja:'豫約',meaning:'자리나 시간 등을 미리 정해 둠',example:'식당에 자리를 예약했어요.'},{word:'약정',hanja:'約定',meaning:'어떤 내용을 서로 의논하여 정함',example:'빌린 자전거를 언제 돌려줄지 약정을 맺었어요.'}],questions:[
 {id:'yak-key',type:'key',title:'두 친구는 무엇을 하고 있을까?',context:'“내일 오후 두 시에 놀이터에서 만나자!”\n“좋아, 꼭 갈게!”',choices:['서로 할 일을 정하고 있어요','물건을 나누고 있어요','지나간 일을 잊고 있어요'],answer:'서로 할 일을 정하고 있어요',explanation:'서로 만날 시간과 장소를 정했어요. 約에는 ‘약속하다’라는 뜻이 있어요.',hints:['두 친구가 언제 만날지 살펴봐요.','둘 다 앞으로 할 일에 동의했어요.']},
 {id:'yak-family',type:'family',title:'세 단어를 이어 주는 뜻은?',context:'약속 · 예약 · 약정',choices:['정하다','달리다','먹다'],answer:'정하다',explanation:'약속·예약·약정에는 모두 約이 있어요. 무엇인가 정한다는 뜻으로 연결돼요.',hints:['각 단어의 뜻에서 반복되는 말을 찾아봐요.','약속은 할 일을, 예약은 자리나 시간을 정해요.']},
 {id:'yak-infer',type:'inference',title:'처음 만난 말, 「협약」',context:'두 학교가 운동장을 함께 쓰기 위한 협약을 맺었어요.',choices:['함께 지킬 내용을 의논해 정한 약속','운동장에서 달리기 시합을 하는 일','학교 건물을 새로 짓는 일'],answer:'함께 지킬 내용을 의논해 정한 약속',explanation:'協(힘을 합할 협) + 約(약속할 약). 협약은 함께 의논하여 맺은 약속이에요.',hints:['約은 서로 정하고 약속한다는 뜻이에요.','두 학교가 운동장을 함께 쓰려면 어떤 약속이 필요할까요?']},
 {id:'yak-context',type:'context',title:'문장 탐정: 무슨 일을 했을까?',context:'우리 반은 “친구의 이야기를 끝까지 듣자”라는 규약을 만들었어요.',choices:['함께 지킬 규칙을 정했어요','친구의 이름을 바꿨어요','이야기책을 샀어요'],answer:'함께 지킬 규칙을 정했어요',explanation:'規(법 규) + 約(약속할 약). 규약은 사람들이 함께 지키기로 정한 규칙이에요.',hints:['‘우리 반’이 함께 지킬 내용을 생각해 봐요.','‘이야기를 끝까지 듣자’는 행동 규칙이에요.']}],chinese:{character:'约',pinyin:'yuē',words:[{word:'约朋友',pinyin:'yuē péngyou',meaning:'친구와 만나기로 하다'},{word:'约时间',pinyin:'yuē shíjiān',meaning:'시간을 정하다'}],sentence:'我们约个时间吧。',pinyinSentence:'Wǒmen yuē ge shíjiān ba.',translation:'우리 시간을 정하자.'}},
 {id:'hak',hanja:'學',sound:'학',meaning:'배울 학',theme:'배움의 숲',icon:'🌳',color:'#dcece7',core:'배우다',description:'배우는 사람, 배우는 곳, 배우는 일을 연결해 봐요.',words:[{word:'학생',hanja:'學生',meaning:'학교에서 배우는 사람',example:'저는 초등학교 학생이에요.'},{word:'학교',hanja:'學校',meaning:'학생들이 모여 배우는 곳',example:'학교에서 친구들과 공부해요.'},{word:'학습',hanja:'學習',meaning:'배워서 익힘',example:'오늘 학습한 내용을 다시 살펴봐요.'}],questions:[
 {id:'hak-key',type:'key',title:'교실에서 무엇을 하고 있을까?',context:'선생님이 새로운 풀이 방법을 알려 주셨어요.\n나는 방법을 이해하고 직접 풀어 봤어요.',choices:['새로운 것을 배우고 있어요','음식을 만들고 있어요','물건을 팔고 있어요'],answer:'새로운 것을 배우고 있어요',explanation:'學은 ‘배우다’라는 뜻이에요. 새로운 것을 이해하는 모습과 연결해 봐요.',hints:['새로운 풀이 방법을 알게 되었어요.','모르던 것을 알게 되는 일이에요.']},
 {id:'hak-family',type:'family',title:'세 단어를 이어 주는 뜻은?',context:'학생 · 학교 · 학습',choices:['배우다','잠자다','나누다'],answer:'배우다',explanation:'학생은 배우는 사람, 학교는 배우는 곳, 학습은 배워서 익히는 일이에요.',hints:['學이 세 단어 모두에 들어 있어요.','사람·장소·활동 모두 공부와 관련 있어요.']},
 {id:'hak-infer',type:'inference',title:'처음 만난 말, 「독학」',context:'민수는 선생님 없이 책을 보며 혼자 기타를 독학했어요.',choices:['스승 없이 혼자 배움','여럿이 함께 공연함','악기를 다른 사람에게 빌림'],answer:'스승 없이 혼자 배움',explanation:'獨(홀로 독) + 學(배울 학). 독학은 스승 없이 스스로 배우는 일이에요.',hints:['學은 배우는 것과 관련 있어요.','‘혼자’와 ‘선생님 없이’가 단서예요.']},
 {id:'hak-context',type:'context',title:'문장 탐정: 어디로 갈까?',context:'누나는 다른 나라의 학교에서 공부하려고 유학을 떠났어요.',choices:['다른 나라로 공부하러 가요','공원으로 산책하러 가요','가게에 물건을 사러 가요'],answer:'다른 나라로 공부하러 가요',explanation:'留學은 다른 나라에 머물며 공부하는 것을 뜻해요. 문장의 ‘다른 나라’와 ‘공부’가 단서예요.',hints:['學의 뜻을 떠올려 봐요.','어디에서 공부하는지 읽어 봐요.']}],chinese:{character:'学',pinyin:'xué',words:[{word:'学中文',pinyin:'xué Zhōngwén',meaning:'중국어를 배우다'},{word:'学画画',pinyin:'xué huàhuà',meaning:'그림 그리기를 배우다'}],sentence:'我喜欢学中文。',pinyinSentence:'Wǒ xǐhuan xué Zhōngwén.',translation:'나는 중국어 배우는 것을 좋아해요.'}},
 {id:'bun',hanja:'分',sound:'분',meaning:'나눌 분',theme:'나눔의 들판',icon:'🌼',color:'#faedc8',core:'나누다',description:'하나를 여럿으로 나누는 뜻이 어디에 숨어 있을까요?',words:[{word:'분리',hanja:'分離',meaning:'서로 나누어 떨어지게 함',example:'종이와 플라스틱을 분리해요.'},{word:'분담',hanja:'分擔',meaning:'일이나 책임을 나누어 맡음',example:'청소할 일을 분담했어요.'},{word:'분배',hanja:'分配',meaning:'몫을 나누어 줌',example:'수확한 감자를 이웃에게 분배했어요.'}],questions:[
 {id:'bun-key',type:'key',title:'친구들은 무엇을 하고 있을까?',context:'네 친구가 큰 빵 하나를 네 조각으로 잘랐어요.\n한 조각씩 먹으려고 해요.',choices:['하나를 여럿으로 나누고 있어요','빵을 굽고 있어요','빵을 숨기고 있어요'],answer:'하나를 여럿으로 나누고 있어요',explanation:'分에는 ‘나누다’라는 뜻이 있어요. 하나를 여러 부분으로 만드는 모습이에요.',hints:['빵은 처음에 하나였어요.','빵이 네 조각이 되었어요.']},
 {id:'bun-family',type:'family',title:'세 단어를 이어 주는 뜻은?',context:'분리 · 분담 · 분배',choices:['나누다','약속하다','배우다'],answer:'나누다',explanation:'물건을 나누고, 일을 나누어 맡고, 몫을 나누어 주는 뜻이에요.',hints:['分이 공통으로 들어 있어요.','한 사람이 모두 맡는 것과 반대예요.']},
 {id:'bun-infer',type:'inference',title:'처음 만난 말, 「분업」',context:'공장에서 사람마다 다른 일을 맡아 물건을 만들어요. 이렇게 분업을 해요.',choices:['일을 나누어 맡아 하는 것','모든 일을 혼자 하는 것','일을 모두 그만두는 것'],answer:'일을 나누어 맡아 하는 것',explanation:'分(나눌 분) + 業(일 업). 분업은 일을 나누어서 맡는 것이에요.',hints:['分은 ‘나누다’예요.','사람마다 다른 일을 맡았어요.']},
 {id:'bun-context',type:'context',title:'문장 탐정: 어떻게 모았을까?',context:'과학 시간에 나뭇잎을 모양에 따라 분류했어요.',choices:['비슷한 특징끼리 나누어 모았어요','모든 나뭇잎을 찢었어요','나뭇잎을 땅에 묻었어요'],answer:'비슷한 특징끼리 나누어 모았어요',explanation:'分(나눌 분) + 類(무리 류). 분류는 공통된 특징에 따라 종류를 나누는 것이에요.',hints:['分의 뜻을 생각해 봐요.','‘모양에 따라’가 나누는 기준이에요.']}],chinese:{character:'分',pinyin:'fēn',words:[{word:'分水果',pinyin:'fēn shuǐguǒ',meaning:'과일을 나누다'},{word:'分成两组',pinyin:'fēn chéng liǎng zǔ',meaning:'두 모둠으로 나누다'}],sentence:'我们分成两组吧。',pinyinSentence:'Wǒmen fēn chéng liǎng zǔ ba.',translation:'우리 두 모둠으로 나누자.'}}
];
