'use strict';
const STORAGE_KEY='meaning-explorer-v1';
const emptyState=()=>({version:1,coins:0,completed:{},records:{},sessions:[]});
let state=emptyState(),storageOK=true;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(parsed.version!==1||!parsed.records||!parsed.completed||!Array.isArray(parsed.sessions)||!Number.isFinite(parsed.coins))throw Error('invalid');state=parsed;}}catch(e){storageOK=false;}
let run=null,view='home',toastTimer;
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
const questions=HANJA_DATA.flatMap(l=>l.questions.map(q=>({...q,lessonId:l.id})));
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;toast('기록을 저장하지 못했어요. 브라우저 저장 설정을 확인해 주세요.');}}
function toast(msg){document.getElementById('toast').textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.getElementById('toast').textContent='',4500);}
function render(html){app.innerHTML=html;document.getElementById('balance').textContent=`✧ ${state.coins}`;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));}
function navigate(target){if(run&&!run.finished&&!confirm('진행 중인 미션을 나갈까요? 완료한 문제 기록은 남지만, 미션은 처음부터 시작해요.'))return;run=null;view=target;if(window.speechSynthesis)speechSynthesis.cancel();({home:home,map:map,report:report}[target]||home)();}
function home(){view='home';render(`<section class="hero"><div><div class="eyebrow">LITTLE WORDS, BIG DISCOVERIES</div><h1>작은 뜻 하나로,<br>넓은 세상을 열어 봐!</h1><p class="muted">한자의 뜻을 열쇠 삼아<br>처음 보는 말도 스스로 알아내는 모험.</p><div class="row"><span class="chip">하루 5~10분 목표</span><span class="chip">뜻 발견 → 연결 → 추리</span></div></div><div class="hero-art" aria-label="뜻 열쇠 약속할 약"><div class="key-tile"><strong>約</strong><span>오늘의 뜻 열쇠</span></div><span class="floating">✦</span><span class="art-label">나만의 어휘 세계가 자라나요</span></div></section><div class="section-head"><h2>어디로 탐험을 떠날까?</h2><span class="muted">체험 미션 3개 · 자유롭게 선택</span></div><div class="lessons">${HANJA_DATA.map((l,i)=>`<article class="lesson"><div class="landscape" style="--tile:${l.color}"><span class="glyph">${l.hanja}</span><span class="plant">${l.icon}</span></div><div class="lesson-body"><span class="eyebrow">0${i+1} · ${state.completed[l.id]?'발견한 열쇠':'새로운 열쇠'}</span><h3>${l.theme}</h3><p>${l.description}</p><button class="primary wide" data-start="${l.id}">${state.completed[l.id]?'다시 탐험하기':'탐험 시작하기'} ↗</button></div></article>`).join('')}</div><div class="note">🔎 <strong>정답보다 발견이 중요해요.</strong> 막히면 힌트를 열어 보세요. 문해력 미션을 마치면 중국어 포털도 열려요.</div>${!storageOK?'<p class="hint">저장된 기록을 읽지 못했어요. 현재는 임시 상태로 시작합니다.</p>':''}`);}
// 이전에 실제로 풀었던 문제만 선정. 오답/최근/오래된 문제를 중복 없이 섞습니다.
function reviewSelection(lessonId){const pool=questions.filter(q=>state.records[q.id]&&q.lessonId!==lessonId);const selected=[];const add=list=>{const q=list.find(x=>!selected.some(s=>s.id===x.id));if(q)selected.push(q);};add([...pool].sort((a,b)=>{const x=state.records[a.id],y=state.records[b.id];return y.wrong/y.attempts-x.wrong/x.attempts;}));add([...pool].sort((a,b)=>state.records[b.id].last-state.records[a.id].last));add([...pool].sort((a,b)=>state.records[a.id].last-state.records[b.id].last));return selected.map(q=>({...q,isReview:true}));}
function start(id){const lesson=HANJA_DATA.find(l=>l.id===id);if(!lesson)return;run={lesson,queue:[...lesson.questions.map(q=>({...q,lessonId:id})),...reviewSelection(id)],index:0,results:[],hint:0,tries:0,finished:false,started:Date.now(),portalDone:false};view='home';showQuestion();}
function showQuestion(){const q=run.queue[run.index];run.hint=0;run.tries=0;run.answered=false;const labels={key:'뜻 열쇠',family:'말 가족',inference:'낯선 말 추리',context:'문장 탐정'};run.choices=shuffle(q.choices);render(`<div class="game"><div class="game-top"><button class="text-btn" data-nav="home">← 탐험 나가기</button><span class="muted">${run.index+1} / ${run.queue.length}</span></div><div class="progress">${run.queue.map((_,i)=>`<i class="${i<=run.index?'done':''}"></i>`).join('')}</div><section class="panel"><div class="eyebrow">${q.isReview?'기억 도전 · 누적복습':labels[q.type]}</div><h2>${q.title}</h2>${q.type==='family'?`<div class="word-grid">${HANJA_DATA.find(l=>l.id===q.lessonId).words.map(w=>`<details class="word-card"><summary>${w.word}<span>${w.hanja}</span></summary><p>${w.meaning}</p><p class="muted">${w.example}</p></details>`).join('')}</div>`:''}<div class="context">${q.context}</div><div class="answers">${run.choices.map((c,i)=>`<button class="answer" data-answer="${i}"><span>${i+1}</span>${c}</button>`).join('')}</div><button class="text-btn" id="hint-btn" data-action="hint">💡 힌트 보기 (0/2)</button><div class="hint" id="hint" role="status"></div><div class="feedback" id="feedback" role="status"></div><button class="primary wide" id="next" data-action="next" hidden>다음 발견으로 →</button></section></div>`);app.focus({preventScroll:true});}
function hint(){if(!run||run.answered)return;const q=run.queue[run.index];if(run.hint<q.hints.length)run.hint++;document.getElementById('hint').textContent=q.hints.slice(0,run.hint).join(' / ');const b=document.getElementById('hint-btn');b.textContent=`💡 힌트 보기 (${run.hint}/2)`;b.disabled=run.hint===q.hints.length;}
function answer(index,button){if(!run||run.answered||button.disabled)return;const q=run.queue[run.index],correct=run.choices[index]===q.answer;run.tries++;if(run.tries===1){const r=state.records[q.id]||{attempts:0,correct:0,wrong:0,hints:0,last:0};r.attempts++;r.correct+=Number(correct);r.wrong+=Number(!correct);r.last=Date.now();state.records[q.id]=r;save();}
if(!correct){button.disabled=true;button.classList.add('wrong');document.getElementById('feedback').textContent='조금 다르게 생각해 볼까? 한자의 뜻과 문장 속 단서를 살펴봐요.';hint();return;}
run.answered=true;state.records[q.id].hints+=Number(run.hint>0);save();run.results.push({id:q.id,first:run.tries===1,hints:run.hint,review:!!q.isReview});document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);button.classList.add('correct');document.getElementById('hint-btn').disabled=true;document.getElementById('feedback').innerHTML=`<strong>✦ 뜻을 발견했어요!</strong><p>${q.explanation}</p>`;document.getElementById('next').hidden=false;}
function next(){if(!run?.answered)return;run.index++;if(run.index<run.queue.length)showQuestion();else complete();}
function complete(){if(!run.finished){const reward=state.completed[run.lesson.id]?.day===dateKey()?0:30;run.reward=reward;state.coins+=reward;const old=state.completed[run.lesson.id];state.completed[run.lesson.id]={day:dateKey(),count:(old?.count||0)+1};state.sessions.push({lessonId:run.lesson.id,at:Date.now(),results:run.results,duration:Date.now()-run.started});state.sessions=state.sessions.slice(-100);run.finished=true;save();}result();}
function result(){const correct=run.results.filter(r=>r.first).length;render(`<div class="game panel center"><div class="eyebrow">MISSION COMPLETE</div><div class="big-glyph">${run.lesson.hanja}</div><h1>오늘의 뜻 열쇠 발견!</h1><p>${run.lesson.core} — 새로운 말과 연결했어요.</p><div class="stats"><div class="stat"><strong>${correct}/${run.results.length}</strong><small>첫 시도 정답</small></div><div class="stat"><strong>${run.results.filter(r=>r.hints).length}</strong><small>힌트로 발견</small></div><div class="stat"><strong>+${run.reward}</strong><small>탐험코인</small></div></div><p class="muted">${run.reward?'끝까지 생각한 노력에 30코인을 드려요.':'오늘 이 미션의 보상은 이미 받았어요. 복습 기록은 남아요.'}</p>${run.queue.some(q=>q.isReview)?'':'<p class="muted">다른 열쇠를 탐험하면 이전 문제가 누적복습으로 등장해요.</p>'}<div class="portal"><h3>그런데, 중국에서는 어떻게 읽을까?</h3><p class="muted">문해력 미션은 완료! 원하면 새로운 말도 만나 봐요.</p><button class="primary wide" data-action="portal">${run.portalDone?'중국어 다시 보기':'중국어 포털 열기'} ↗</button></div><button class="secondary wide" data-nav="map">내 어휘 지도 보기</button><button class="text-btn" data-nav="home">오늘은 여기까지</button></div>`);}
function portal(){const c=run.lesson.chinese;render(`<div class="game panel"><div class="eyebrow">BONUS · 중국어 포털</div><h2>같은 뜻, 새로운 소리</h2><div class="center"><div class="big-glyph">${run.lesson.hanja} → ${c.character}</div><div class="pinyin">${c.pinyin}</div></div>${c.words.map((w,i)=>`<div class="portal"><div class="chinese-line"><strong lang="zh-CN">${w.word}</strong><button class="secondary" data-speak="${i}" aria-label="${w.word} 듣기">▶ 듣기</button></div><div class="pinyin">${w.pinyin}</div><p>${w.meaning}</p></div>`).join('')}<div class="note"><strong>듣고 내 목소리로 말해 봐요.</strong><p lang="zh-CN">${c.sentence}</p><p class="pinyin">${c.pinyinSentence}</p><p>${c.translation}</p><button class="text-btn" data-speak="sentence">▶ 문장 듣기</button></div><p class="muted">음성은 기기의 중국어 음성을 사용해요. 음성 인식·발음 채점은 하지 않아요.</p><button class="primary wide" data-action="portal-finish">따라 말했어요 · 마치기 ✓</button><button class="text-btn" data-action="result">결과로 돌아가기</button></div>`);}
function speak(key){if(!('speechSynthesis'in window)){toast('이 브라우저는 음성을 지원하지 않아요. 병음을 보고 읽어 주세요.');return;}const c=run.lesson.chinese;const u=new SpeechSynthesisUtterance(key==='sentence'?c.sentence:c.words[Number(key)].word);u.lang='zh-CN';u.rate=.8;const v=speechSynthesis.getVoices().find(v=>/^zh[-_]CN/i.test(v.lang))||speechSynthesis.getVoices().find(v=>/^zh/i.test(v.lang));if(v)u.voice=v;u.onerror=()=>toast('중국어 음성을 재생하지 못했어요. 기기의 음성 설정을 확인해 주세요.');speechSynthesis.cancel();speechSynthesis.speak(u);}
function map(){view='map';render(`<div class="eyebrow">MY WORD WORLD</div><h1>내가 넓힌 말의 세계</h1><p class="muted">발견한 뜻 열쇠 ${Object.keys(state.completed).length} / ${HANJA_DATA.length} · 미션을 완료하면 단어의 길이 열려요.</p>${HANJA_DATA.map(l=>`<section class="map-card"><div class="chinese-line"><h2>${l.icon} ${l.hanja} · ${l.theme}</h2><span class="chip">${state.completed[l.id]?'발견 완료':'아직 탐험 전'}</span></div>${state.completed[l.id]?`<p>${l.hanja}의 뜻 열쇠: <strong>${l.core}</strong></p><div class="word-nodes">${l.words.map(w=>`<span>${w.word} · ${w.hanja}</span>`).join('')}</div>`:'<p class="muted">탐험을 마치면 연결한 말들이 나타나요.</p>'}<button class="secondary wide" data-start="${l.id}">이 열쇠 탐험하기 →</button></section>`).join('')}`);}
function report(){view='report';const played=questions.filter(q=>state.records[q.id]);const totals=played.reduce((a,q)=>{const r=state.records[q.id];a.attempts+=r.attempts;a.correct+=r.correct;return a;},{attempts:0,correct:0});render(`<div class="eyebrow">COACHING CARD</div><h1>어떤 뜻을 발견했을까요?</h1><p class="muted">이 기기의 학습 기록입니다. 정답률은 각 문제의 첫 응답으로 계산해요.</p><div class="stats"><div class="stat"><strong>${state.sessions.length}</strong><small>완료 미션 · 최근 100회</small></div><div class="stat"><strong>${totals.attempts?Math.round(totals.correct/totals.attempts*100):0}%</strong><small>첫 시도 정답률</small></div><div class="stat"><strong>${played.filter(q=>state.records[q.id].wrong).length}</strong><small>오답 경험 문제</small></div></div><section class="panel"><h2>다음 코칭에서 살펴볼 것</h2>${played.filter(q=>state.records[q.id].wrong||state.records[q.id].hints).map(q=>`<p>• ${HANJA_DATA.find(l=>l.id===q.lessonId).hanja} · ${q.title}<br><small class="muted">첫 응답 오답 ${state.records[q.id].wrong}회 · 힌트 후 완료 ${state.records[q.id].hints}회</small></p>`).join('')||'<p class="muted">아직 확인할 항목이 없어요. 미션을 진행해 주세요.</p>'}<div class="table-wrap"><table><thead><tr><th>문제</th><th>첫 정답/학습</th><th>최근 학습</th></tr></thead><tbody>${played.map(q=>{const r=state.records[q.id];return `<tr><td>${q.title}</td><td>${r.correct}/${r.attempts}</td><td>${new Date(r.last).toLocaleDateString('ko-KR')}</td></tr>`;}).join('')}</tbody></table></div><button class="secondary wide" data-action="export">학습 기록 JSON 내려받기</button></section><div class="note">여러 학생이 한 브라우저를 사용하면 기록이 합쳐져요. 이 체험판에는 학생 로그인과 교사 원격 조회가 없습니다.</div>`);}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`learning-record-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.nav){navigate(b.dataset.nav);return;}if(b.dataset.start){start(b.dataset.start);return;}if(b.dataset.answer!==undefined){answer(Number(b.dataset.answer),b);return;}if(b.dataset.speak!==undefined){speak(b.dataset.speak);return;}const actions={hint,next,portal,result,export:exportData,'portal-finish':()=>{run.portalDone=true;if(window.speechSynthesis)speechSynthesis.cancel();result();}};actions[b.dataset.action]?.();});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();navigate('home');});
home();
