'use strict';
const STORAGE_KEY='meaning-explorer-v1';
const emptyState=()=>({version:1,coins:0,completed:{},records:{},sessions:[]});
let state=emptyState(),storageOK=true;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(parsed.version!==1||!parsed.records||!parsed.completed||!Array.isArray(parsed.sessions)||!Number.isFinite(parsed.coins))throw Error('invalid');state=parsed;}}catch(e){storageOK=false;}
let run=null,view='home',toastTimer;
let writing=null;
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
const questions=HANJA_DATA.flatMap(l=>l.questions.map(q=>({...q,lessonId:l.id})));
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;toast('기록을 저장하지 못했어요. 브라우저 저장 설정을 확인해 주세요.');}}
function toast(msg){document.getElementById('toast').textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.getElementById('toast').textContent='',4500);}
function render(html){stopWriting();app.innerHTML=html;document.getElementById('balance').textContent=`조사 포인트 ${state.coins}`;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));}
function navigate(target){if(run&&!run.finished&&!confirm('진행 중인 미션을 나갈까요? 완료한 문제 기록은 남지만, 미션은 처음부터 시작해요.'))return;run=null;view=target;if(window.speechSynthesis)speechSynthesis.cancel();({home:home,map:map,report:report}[target]||home)();}
const CASES={yak:{title:'사라진 약속 메모',tag:'시간과 약속',brief:'친구들이 만나기로 한 메모가 사라졌어요. 남아 있는 말들을 살펴보고, 서로 무엇을 정했는지 알아봐요.',number:'01'},hak:{title:'혼자 배우는 사람의 비밀',tag:'사람과 배움',brief:'혼자 책을 보며 기타를 배우는 친구가 있어요. 배움과 관련된 말들을 모아 이 친구의 공부 방법을 알아봐요.',number:'02'},bun:{title:'뒤섞인 작업실',tag:'분류와 나눔',brief:'작업실의 물건과 할 일이 뒤섞였어요. 나누는 뜻이 담긴 말들을 찾아 정리 방법을 알아봐요.',number:'03'}};
function home(){view='home';const solved=Object.keys(state.completed).length;render(`<section class="desk-hero"><div><div class="eyebrow">JINDAM · WORD DETECTIVE BUREAU</div><h1>모르는 말?<br><em>단서를 찾으면 돼!</em></h1><p>아는 한자의 뜻을 연결해서<br>말 속에 숨은 의미를 밝혀 보자.</p><div class="hero-meta"><span>하루 5~10분</span><span>읽고 · 연결하고 · 추리하기</span></div></div><div class="desk-art" aria-hidden="true"><div class="paper-slip slip-back">단서 02<br><b>예약</b><small>미리 정해 두는 일</small></div><div class="paper-slip slip-front"><span>단서 01</span><strong>約</strong><small>서로 정하다</small></div><div class="magnifier"></div><span class="stamp">뜻을 찾아라!</span></div></section><section class="office-bar"><span><b>${String(solved).padStart(2,'0')}</b> / 03 사건 완료</span><span>오늘도 한 가지 뜻을 발견해 봐요.</span></section><div class="section-head"><h2>접수된 사건</h2><span class="muted">조사할 파일을 골라요</span></div><div class="case-list">${HANJA_DATA.map(l=>{const c=CASES[l.id];return `<button class="case-file" data-case="${l.id}"><span class="file-number">CASE<br><b>${c.number}</b></span><span class="file-copy"><span class="case-tag">${c.tag}</span><strong>${c.title}</strong><small>${l.description}</small></span><span class="file-status ${state.completed[l.id]?'solved':''}">${state.completed[l.id]?'조사 완료':'조사 시작'} <span>↗</span></span></button>`;}).join('')}</div><div class="note"><strong>탐정 수칙 01</strong><p>모르면 힌트를 펼쳐요. 단서를 연결하는 과정이 중요해요.</p></div>${!storageOK?'<p class="hint">기록을 저장할 수 없는 상태예요.</p>':''}`);}
function caseBrief(id){const l=HANJA_DATA.find(l=>l.id===id);if(!l)return;const c=CASES[id];render(`<section class="brief panel game"><div class="eyebrow">CASE ${c.number} · 사건 의뢰서</div><h1>${c.title}</h1><p class="context">${c.brief}</p><h3>오늘의 조사 순서</h3><ol class="case-steps"><li><b>단서 발견</b><span>상황을 읽고 한자의 뜻 찾기</span></li><li><b>글자 기록</b><span>한 획씩 따라 쓰며 살펴보기</span></li><li><b>증거 연결</b><span>생활어휘의 공통점 찾기</span></li><li><b>뜻 추리</b><span>새로운 단어와 문장의 뜻 풀기</span></li></ol><p class="muted">이전 학습 기록이 있으면 복습도 이어져요.<br>조사가 끝나면 중국어 통신실을 열 수 있어요.</p><button class="primary wide" data-start="${id}">이 사건 조사하기 →</button><button class="text-btn wide" data-nav="home">사건 접수대로 돌아가기</button></section>`);}
// 이전에 실제로 풀었던 문제만 선정. 오답/최근/오래된 문제를 중복 없이 섞습니다.
function reviewSelection(lessonId){const pool=questions.filter(q=>state.records[q.id]&&q.lessonId!==lessonId);const selected=[];const add=list=>{const q=list.find(x=>!selected.some(s=>s.id===x.id));if(q)selected.push(q);};add([...pool].sort((a,b)=>{const x=state.records[a.id],y=state.records[b.id];return y.wrong/y.attempts-x.wrong/x.attempts;}));add([...pool].sort((a,b)=>state.records[b.id].last-state.records[a.id].last));add([...pool].sort((a,b)=>state.records[a.id].last-state.records[b.id].last));return selected.map(q=>({...q,isReview:true}));}
function start(id){const lesson=HANJA_DATA.find(l=>l.id===id);if(!lesson)return;run={lesson,queue:[...lesson.questions.map(q=>({...q,lessonId:id})),...reviewSelection(id)],index:0,results:[],hint:0,tries:0,finished:false,started:Date.now(),portalDone:false};view='home';showQuestion();}
function showQuestion(){const q=run.queue[run.index];run.hint=0;run.tries=0;run.answered=false;const labels={key:'01 · 단서 발견',family:'02 · 증거 연결',inference:'03 · 뜻 추리',context:'04 · 문맥 조사'};run.choices=shuffle(q.choices);render(`<div class="game"><div class="game-top"><button class="text-btn" data-nav="home">← 사건 접수대</button><span class="muted">${run.index+1} / ${run.queue.length}</span></div><div class="progress">${run.queue.map((_,i)=>`<i class="${i<=run.index?'done':''}"></i>`).join('')}</div><section class="panel investigation"><div class="case-ribbon">CASE ${CASES[run.lesson.id].number} / ${CASES[run.lesson.id].title}</div><div class="eyebrow">${q.isReview?'기록 재검토 · 누적복습':labels[q.type]}</div><h2>${q.title}</h2>${q.type==='family'?`<div class="word-grid">${HANJA_DATA.find(l=>l.id===q.lessonId).words.map(w=>`<details class="word-card"><summary>${w.word}<span>${w.hanja}</span></summary><p>${w.meaning}</p><p class="muted">${w.example}</p></details>`).join('')}</div>`:''}<div class="context">${q.context}</div><div class="answers">${run.choices.map((c,i)=>`<button class="answer" data-answer="${i}"><span>${i+1}</span>${c}</button>`).join('')}</div><button class="text-btn" id="hint-btn" data-action="hint">💡 힌트 보기 (0/2)</button><div class="hint" id="hint" role="status"></div><div class="feedback" id="feedback" role="status"></div><button class="primary wide" id="next" data-action="next" hidden>다음 단서로 →</button></section></div>`);app.focus({preventScroll:true});}
function hint(){if(!run||run.answered)return;const q=run.queue[run.index];if(run.hint<q.hints.length)run.hint++;document.getElementById('hint').textContent=q.hints.slice(0,run.hint).join(' / ');const b=document.getElementById('hint-btn');b.textContent=`💡 힌트 보기 (${run.hint}/2)`;b.disabled=run.hint===q.hints.length;}
function answer(index,button){if(!run||run.answered||button.disabled)return;const q=run.queue[run.index],correct=run.choices[index]===q.answer;run.tries++;if(run.tries===1){const r=state.records[q.id]||{attempts:0,correct:0,wrong:0,hints:0,last:0};r.attempts++;r.correct+=Number(correct);r.wrong+=Number(!correct);r.last=Date.now();state.records[q.id]=r;save();}
if(!correct){button.disabled=true;button.classList.add('wrong');document.getElementById('feedback').textContent='조금 다르게 생각해 볼까? 한자의 뜻과 문장 속 단서를 살펴봐요.';hint();return;}
run.answered=true;state.records[q.id].hints+=Number(run.hint>0);save();run.results.push({id:q.id,first:run.tries===1,hints:run.hint,review:!!q.isReview});document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);button.classList.add('correct');document.getElementById('hint-btn').disabled=true;document.getElementById('feedback').innerHTML=`<strong>✓ 단서를 풀었어요!</strong><p>${q.explanation}</p>`;document.getElementById('next').hidden=false;}
function next(){if(!run?.answered)return;if(run.index===0&&!run.writingOffered){run.writingOffered=true;showWriting(run.lesson.hanja,()=>{run.index++;showQuestion();});return;}run.index++;if(run.index<run.queue.length)showQuestion();else complete();}
function complete(){if(!run.finished){const reward=state.completed[run.lesson.id]?.day===dateKey()?0:30;run.reward=reward;state.coins+=reward;const old=state.completed[run.lesson.id];state.completed[run.lesson.id]={day:dateKey(),count:(old?.count||0)+1};state.sessions.push({lessonId:run.lesson.id,at:Date.now(),results:run.results,duration:Date.now()-run.started});state.sessions=state.sessions.slice(-100);run.finished=true;save();}result();}
function result(){const correct=run.results.filter(r=>r.first).length;render(`<div class="game panel center"><div class="eyebrow">CASE CLOSED · 조사 완료</div><div class="big-glyph">${run.lesson.hanja}</div><h1>사건 조사 완료!</h1><p>${run.lesson.core} — 새로운 말과 연결했어요.</p><div class="stats"><div class="stat"><strong>${correct}/${run.results.length}</strong><small>첫 시도 정답</small></div><div class="stat"><strong>${run.results.filter(r=>r.hints).length}</strong><small>힌트로 발견</small></div><div class="stat"><strong>+${run.reward}</strong><small>탐정 포인트</small></div></div><p class="muted">${run.reward?'끝까지 생각한 노력에 30포인트을 드려요.':'오늘 이 미션의 보상은 이미 받았어요. 복습 기록은 남아요.'}</p>${run.queue.some(q=>q.isReview)?'':'<p class="muted">다른 사건을 조사하면 이전 문제가 누적복습으로 등장해요.</p>'}<div class="portal"><h3>그런데, 중국에서는 어떻게 읽을까?</h3><p class="muted">문해력 미션은 완료! 원하면 새로운 말도 만나 봐요.</p><button class="primary wide" data-action="portal">${run.portalDone?'중국어 다시 보기':'중국어 통신실 열기'} ↗</button></div><button class="secondary wide" data-nav="map">증거 보관함 보기</button><button class="text-btn" data-nav="home">오늘은 여기까지</button></div>`);}
function portal(){const c=run.lesson.chinese;render(`<div class="game panel"><div class="eyebrow">BONUS · 중국어 통신실</div><h2>같은 뜻, 새로운 소리</h2><div class="center"><div class="big-glyph">${run.lesson.hanja} → ${c.character}</div><div class="pinyin">${c.pinyin}</div></div>${c.words.map((w,i)=>`<div class="portal"><div class="chinese-line"><strong lang="zh-CN">${w.word}</strong><button class="secondary" data-speak="${i}" aria-label="${w.word} 듣기">▶ 듣기</button></div><div class="pinyin">${w.pinyin}</div><p>${w.meaning}</p></div>`).join('')}<div class="note"><strong>듣고 내 목소리로 말해 봐요.</strong><p lang="zh-CN">${c.sentence}</p><p class="pinyin">${c.pinyinSentence}</p><p>${c.translation}</p><button class="text-btn" data-speak="sentence">▶ 문장 듣기</button></div><p class="muted">음성은 기기의 중국어 음성을 사용해요. 음성 인식·발음 채점은 하지 않아요.</p><button class="secondary wide" data-action="portal-write">✍ 중국어 글자도 따라 쓰기</button><button class="primary wide" data-action="portal-finish">따라 말했어요 · 마치기 ✓</button><button class="text-btn" data-action="result">결과로 돌아가기</button></div>`);}
function speak(key){if(!('speechSynthesis'in window)){toast('이 브라우저는 음성을 지원하지 않아요. 병음을 보고 읽어 주세요.');return;}const c=run.lesson.chinese;const u=new SpeechSynthesisUtterance(key==='sentence'?c.sentence:c.words[Number(key)].word);u.lang='zh-CN';u.rate=.8;const v=speechSynthesis.getVoices().find(v=>/^zh[-_]CN/i.test(v.lang))||speechSynthesis.getVoices().find(v=>/^zh/i.test(v.lang));if(v)u.voice=v;u.onerror=()=>toast('중국어 음성을 재생하지 못했어요. 기기의 음성 설정을 확인해 주세요.');speechSynthesis.cancel();speechSynthesis.speak(u);}
function map(){view='map';render(`<div class="eyebrow">EVIDENCE ARCHIVE</div><h1>내가 모은 뜻의 증거</h1><p class="muted">조사를 마친 사건 ${Object.keys(state.completed).length} / ${HANJA_DATA.length} · 미션을 완료하면 말의 연결 기록이 남아요.</p>${HANJA_DATA.map(l=>`<section class="map-card"><div class="chinese-line"><h2>${l.hanja} · ${CASES[l.id].title}</h2><span class="chip">${state.completed[l.id]?'조사 완료':'아직 조사 전'}</span></div>${state.completed[l.id]?`<p>${l.hanja}의 핵심 단서: <strong>${l.core}</strong></p><div class="word-nodes">${l.words.map(w=>`<span>${w.word} · ${w.hanja}</span>`).join('')}</div>`:'<p class="muted">조사를 마치면 연결한 말들이 나타나요.</p>'}<button class="secondary wide" data-start="${l.id}">이 사건 다시 살펴보기 →</button></section>`).join('')}`);}
function report(){view='report';const played=questions.filter(q=>state.records[q.id]);const totals=played.reduce((a,q)=>{const r=state.records[q.id];a.attempts+=r.attempts;a.correct+=r.correct;return a;},{attempts:0,correct:0});render(`<div class="eyebrow">COACHING CARD</div><h1>어떤 뜻을 발견했을까요?</h1><p class="muted">이 기기의 학습 기록입니다. 정답률은 각 문제의 첫 응답으로 계산해요.</p><div class="stats"><div class="stat"><strong>${state.sessions.length}</strong><small>완료 미션 · 최근 100회</small></div><div class="stat"><strong>${totals.attempts?Math.round(totals.correct/totals.attempts*100):0}%</strong><small>첫 시도 정답률</small></div><div class="stat"><strong>${played.filter(q=>state.records[q.id].wrong).length}</strong><small>오답 경험 문제</small></div></div><section class="panel"><h2>따라 쓰기 기록</h2><p class="muted">획 경로 연습 완료 횟수입니다. 글씨의 아름다움이나 독립 쓰기 실력을 평가하지 않아요.</p>${Object.entries(state.writing||{}).map(([char,r])=>`<p>${esc(char)} · 완료 ${r.completed}회 · 최근 ${new Date(r.last).toLocaleDateString('ko-KR')}</p>`).join('')||'<p class="muted">아직 완료한 쓰기 연습이 없어요.</p>'}<h2>다음 코칭에서 살펴볼 것</h2>${played.filter(q=>state.records[q.id].wrong||state.records[q.id].hints).map(q=>`<p>• ${HANJA_DATA.find(l=>l.id===q.lessonId).hanja} · ${q.title}<br><small class="muted">첫 응답 오답 ${state.records[q.id].wrong}회 · 힌트 후 완료 ${state.records[q.id].hints}회</small></p>`).join('')||'<p class="muted">아직 확인할 항목이 없어요. 미션을 진행해 주세요.</p>'}<div class="table-wrap"><table><thead><tr><th>문제</th><th>첫 정답/학습</th><th>최근 학습</th></tr></thead><tbody>${played.map(q=>{const r=state.records[q.id];return `<tr><td>${q.title}</td><td>${r.correct}/${r.attempts}</td><td>${new Date(r.last).toLocaleDateString('ko-KR')}</td></tr>`;}).join('')}</tbody></table></div><button class="secondary wide" data-action="export">학습 기록 JSON 내려받기</button></section><div class="note">여러 학생이 한 브라우저를 사용하면 기록이 합쳐져요. 이 체험판에는 학생 로그인과 교사 원격 조회가 없습니다.</div>`);}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`learning-record-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.nav){navigate(b.dataset.nav);return;}if(b.dataset.case){caseBrief(b.dataset.case);return;}if(b.dataset.start){start(b.dataset.start);return;}if(b.dataset.answer!==undefined){answer(Number(b.dataset.answer),b);return;}if(b.dataset.speak!==undefined){speak(b.dataset.speak);return;}const actions={hint,next,portal,result,'portal-write':()=>showWriting(run.lesson.chinese.character,portal),export:exportData,'portal-finish':()=>{run.portalDone=true;if(window.speechSynthesis)speechSynthesis.cancel();result();}};actions[b.dataset.action]?.();});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();navigate('home');});
home();

// Writing stays separate from vocabulary scoring. Source coordinates: y-up, top=900.
function stopWriting(){if(writing){cancelAnimationFrame(writing.frame);writing=null;}}
function sampleLine(points,n=32){
 const lengths=[0];for(let i=1;i<points.length;i++)lengths.push(lengths[i-1]+Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]));
 const total=lengths.at(-1);if(!total)return Array.from({length:n},()=>points[0]);
 return Array.from({length:n},(_,i)=>{const target=total*i/(n-1);let j=1;while(j<lengths.length-1&&lengths[j]<target)j++;const t=(target-lengths[j-1])/(lengths[j]-lengths[j-1]||1);return points[j-1].map((x,k)=>x+(points[j][k]-x)*t);});
}
function matchesStroke(points,median){
 if(points.length<3)return false;
 const length=ps=>ps.slice(1).reduce((sum,p,i)=>sum+Math.hypot(p[0]-ps[i][0],p[1]-ps[i][1]),0);
 const ratio=length(points)/length(median);if(ratio<.55||ratio>1.9)return false;
 const first=points[0],last=points.at(-1),start=median[0],end=median.at(-1);
 if((last[0]-first[0])*(end[0]-start[0])+(last[1]-first[1])*(end[1]-start[1])<=0)return false;
 const a=sampleLine(points),b=sampleLine(median);const distances=a.map((p,i)=>Math.hypot(p[0]-b[i][0],p[1]-b[i][1]));
 return distances[0]<105&&distances.at(-1)<115&&Math.max(...distances)<165&&distances.reduce((x,y)=>x+y,0)/distances.length<85;
}
function showWriting(character,onDone){
 const data=STROKE_DATA[character];if(!data){onDone();return;}
 render(`<section class="game panel writing-panel"><div class="eyebrow">글자 단서 기록 · 따라 쓰기</div><h2>${character} · 한 획씩 따라 써요</h2><p class="muted">주황색 점에서 시작해 화살표 방향으로 그어 보세요.<br>손가락·펜·마우스로 쓸 수 있어요.</p><div class="writing-board"><canvas id="writing-canvas" width="1024" height="1024" aria-label="${character} 따라 쓰기 연습장"></canvas></div><p id="writing-status" role="status" aria-live="polite"></p><div class="row"><button class="secondary" id="writing-demo">현재 획 보기 ▶</button><button class="secondary" id="writing-reset">처음부터 다시</button></div><button class="primary wide" id="writing-next" disabled>한 획씩 완성해 봐요</button><button class="text-btn" id="writing-skip">이번에는 건너뛰기 →</button><details class="muted"><summary>연습 안내</summary>이 체험판은 중국어 자형·획순 자료를 사용해요. 한국 한자 교재의 자형·획순과 다를 수 있어요. 경로를 따라 쓰는 연습이며 정밀 필기 채점은 아니에요.</details></section>`);
 const canvas=document.getElementById('writing-canvas');
 const w=writing={character,data,index:0,points:[],pointer:null,frame:0,demo:false,recorded:false,canvas,ctx:canvas.getContext('2d')};
 const status=document.getElementById('writing-status');
 const update=msg=>{status.textContent=msg||`${w.index+1} / ${data.strokes.length}획 · 주황색 점에서 출발!`;};
 const coords=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)/r.width*1024,900-(e.clientY-r.top)/r.height*1024];};
 const cancel=()=>{w.pointer=null;w.points=[];drawWriting(w);};
 canvas.addEventListener('pointerdown',e=>{if(w.demo||w.index>=data.strokes.length||w.pointer!==null||e.button>0)return;e.preventDefault();w.pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);w.points=[coords(e)];drawWriting(w);});
 canvas.addEventListener('pointermove',e=>{if(w.pointer!==e.pointerId)return;e.preventDefault();w.points.push(coords(e));drawWriting(w);});
 canvas.addEventListener('pointerup',e=>{if(w.pointer!==e.pointerId)return;w.points.push(coords(e));w.pointer=null;
  if(matchesStroke(w.points,data.medians[w.index])){w.index++;if(w.index===data.strokes.length){if(!w.recorded){state.writing||={};const r=state.writing[character]||{completed:0};r.completed++;r.last=Date.now();state.writing[character]=r;w.recorded=true;save();}update('✦ 한 글자 완성! 글자 단서를 기록했어요.');const b=document.getElementById('writing-next');b.disabled=false;b.textContent='완성했어요 · 다음으로 →';document.getElementById('writing-demo').disabled=true;}else update('좋아요! 이제 '+(w.index+1)+'번째 획을 이어 써 봐요.');}
  else update('괜찮아요! 주황색 점에서 시작해 끝까지 천천히 따라가 봐요.');
  w.points=[];drawWriting(w);
 });
 canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',()=>{if(w.pointer!==null)cancel();});
 document.getElementById('writing-reset').onclick=()=>{cancelAnimationFrame(w.frame);w.demo=false;w.index=0;w.pointer=null;w.points=[];document.getElementById('writing-next').disabled=true;document.getElementById('writing-next').textContent='한 획씩 완성해 봐요';document.getElementById('writing-demo').disabled=false;update();drawWriting(w);};
 document.getElementById('writing-demo').onclick=()=>{if(w.demo||w.index>=data.strokes.length)return;w.pointer=null;w.points=[];w.demo=true;const pts=sampleLine(data.medians[w.index],80),start=performance.now();const tick=time=>{if(writing!==w)return;const progress=Math.min(1,(time-start)/1400);w.points=pts.slice(0,Math.max(1,Math.ceil(progress*pts.length)));drawWriting(w);if(progress<1)w.frame=requestAnimationFrame(tick);else{w.demo=false;w.points=[];drawWriting(w);}};w.frame=requestAnimationFrame(tick);};
 document.getElementById('writing-next').onclick=()=>{if(w.index===data.strokes.length)onDone();};
 document.getElementById('writing-skip').onclick=onDone;
 update();drawWriting(w);app.focus({preventScroll:true});
}
function drawWriting(w){
 const c=w.ctx;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,1024,1024);c.strokeStyle='#dfe5d7';c.lineWidth=3;c.setLineDash([12,12]);c.beginPath();c.moveTo(512,0);c.lineTo(512,1024);c.moveTo(0,512);c.lineTo(1024,512);c.moveTo(0,0);c.lineTo(1024,1024);c.moveTo(1024,0);c.lineTo(0,1024);c.stroke();c.setLineDash([]);
 c.setTransform(1,0,0,-1,0,900);w.data.strokes.forEach((path,i)=>{c.fillStyle=i<w.index?'#263650':i===w.index?'#d9e0ec':'#eeece6';c.fill(new Path2D(path));});
 if(w.index<w.data.medians.length){const m=w.data.medians[w.index],a=m[0],samples=sampleLine(m),b=samples[7];c.strokeStyle='#c18526';c.lineWidth=7;c.lineCap='round';c.setLineDash([10,13]);c.beginPath();m.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();c.setLineDash([]);c.fillStyle='#d39228';c.beginPath();c.arc(...a,18,0,Math.PI*2);c.fill();const angle=Math.atan2(b[1]-a[1],b[0]-a[0]);c.beginPath();c.moveTo(...b);c.lineTo(b[0]-24*Math.cos(angle-.55),b[1]-24*Math.sin(angle-.55));c.moveTo(...b);c.lineTo(b[0]-24*Math.cos(angle+.55),b[1]-24*Math.sin(angle+.55));c.stroke();}
 if(w.points.length){c.strokeStyle=w.demo?'#d39228':'#416d94';c.lineWidth=24;c.lineJoin='round';c.lineCap='round';c.beginPath();w.points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();}
}
