'use strict';
const STORAGE_KEY='meaning-detective-v3',LEGACY_KEY='meaning-explorer-v1';
const app=document.getElementById('app'),dialog=document.getElementById('dialog');
const emptyState=()=>({version:3,week:1,coins:0,completed:{},records:{},writing:{},sessions:[],active:null,settings:{practice:3}});
let state=emptyState(),storageOK=true,view='home',writing=null,toastTimer,reportPage=0,weekPage=0,portalIndex=0,portalLesson=null,practice=null,modalReturn=null,audio=null;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const p=JSON.parse(raw);if(p.version!==3||!p.records||!p.completed||!Array.isArray(p.sessions))throw Error();state={...state,...p};}else{const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(old){state.records=old.records||{};state.writing=old.writing||{};state.coins=old.coins||0;state.legacy=old;}}}catch(e){storageOK=false;}
const lessonById=id=>HANJA_DATA.find(l=>l.id===id),weekById=id=>WEEKS.find(w=>w.id===Number(id))||WEEKS[0];
const questions=HANJA_DATA.flatMap(l=>l.questions.map(q=>({...q,lessonId:l.id})));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;toast('기록을 저장하지 못했어요. 설정에서 기록을 내려받아 주세요.');}}
function toast(message){document.getElementById('toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.getElementById('toast').textContent='',4500);}
function stopAudio(){if(audio){audio.pause();audio=null;}if(window.speechSynthesis)speechSynthesis.cancel();}
function render(html){stopWriting();stopAudio();app.innerHTML=html;document.querySelectorAll('nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));app.focus({preventScroll:true});}
function openModal(title,html){dialog.dataset.kind=title==='연습 설정'?'settings':title==='사용 안내'?'info':'general';modalReturn=document.activeElement;document.getElementById('dialog-body').innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button data-action="close" aria-label="팝업 닫기">×</button></div>${html}`;if(!dialog.open)dialog.showModal();}
function closeModal(){dialog.close();if(modalReturn?.isConnected)modalReturn.focus({preventScroll:true});}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function navigate(target){closeModal();save();practice=null;view=target;({home,report}[target]||home)();}
const doneCount=w=>w.lessons.filter(id=>state.completed[id]).length;
const puzzlePath='M12 18 H35 C29 3 56 3 50 18 H80 V39 C96 33 96 59 80 53 V80 H58 C64 96 38 96 44 80 H12 V57 C-4 63 -4 37 12 43 Z';
function home(){view='home';const w=weekById(state.week),n=doneCount(w),next=w.lessons.find(id=>!state.completed[id])||w.lessons[0];render(`<section class="screen home-screen" style="--accent:${w.color}"><div class="row spread"><span class="eyebrow">FIVE CLUES, ONE PUZZLE</span><button class="pill" data-action="weeks">${w.id}주차 바꾸기 ▾</button></div><div class="week-heading"><h1>${w.title}</h1><p class="muted">${n===5?'다섯 조각 완성! 이번 주 공부를 마쳤어요.':'한 글자씩 알아내며 퍼즐을 맞춰 봐요.'}</p></div><div class="puzzle-board" aria-label="${w.id}주차 한자 퍼즐">${w.lessons.map(id=>{const l=lessonById(id),done=!!state.completed[id],active=state.active?.lessonId===id;return `<button class="piece ${done?'complete':active?'in-progress':''}" data-lesson="${id}" aria-label="${l.hanja} ${l.meaning}, ${done?'학습 완료':active?'진행 중':'시작 전'}"><svg viewBox="-8 0 108 102" aria-hidden="true"><path d="${puzzlePath}"/></svg><span class="piece-content"><strong>${l.hanja}</strong><small>${l.meaning}</small><small>${done?'학습 완료 ✓':active?'이어서 공부':'조각 맞추기'}</small></span></button>`;}).join('')}</div><div class="row spread tiny"><b>${n===5?'✓ '+w.id+'주차 학습 완료':'모은 조각 '+n+' / 5'}</b><span>${state.coins} 포인트</span></div><div class="weekly-progress"><i style="width:${n*20}%"></i></div><div class="home-bottom"><button class="primary wide" ${state.active?'data-action="resume"':`data-lesson="${next}"`}>${state.active?'하던 공부 이어하기':n===5?'한 번 더 복습하기':'오늘의 조각 맞추기'} <span>→</span></button><p class="tiny muted center">뜻 발견 · 어휘 연결 · 뜻 추리 · 나눠 쓰기 3회</p>${!storageOK?'<p class="tiny">⚠ 지금은 기록 저장을 확인할 수 없어요.</p>':''}</div></section>`);}
function weeks(page=0){weekPage=Math.max(0,Math.min(Math.ceil(WEEKS.length/4)-1,page));openModal('주차 퍼즐 고르기',`<p class="muted">원하는 주차를 골라요. 다섯 글자를 끝내면 완성!</p><div class="week-grid">${WEEKS.slice(weekPage*4,weekPage*4+4).map(w=>`<button class="week-tile ${w.id===state.week?'current':''}" data-week="${w.id}" style="--accent:${w.color}"><strong>${w.icon} ${w.id}주차</strong><p>${w.title}</p><div class="mini-pieces" aria-hidden="true">${w.lessons.map(id=>`<i class="${state.completed[id]?'done':''}"></i>`).join('')}</div><small>${doneCount(w)===5?'✓ 학습 완료':doneCount(w)+' / 5 조각'}</small></button>`).join('')}</div>${WEEKS.length>4?`<div class="pager"><button data-weekpage="${weekPage-1}" ${weekPage===0?'disabled':''}>← 이전</button><span>${weekPage+1} / ${Math.ceil(WEEKS.length/4)}</span><button data-weekpage="${weekPage+1}" ${(weekPage+1)*4>=WEEKS.length?'disabled':''}>다음 →</button></div>`:''}<p class="tiny muted">현재 ${WEEKS.length}주차 · ${HANJA_DATA.length}자 수록</p>`);}
function selectLesson(id){const l=lessonById(id);if(!l)return;if(state.active?.lessonId===id){resume();return;}if(state.active){openModal('공부를 바꿀까요?',`<p class="dialog-body-text">${lessonById(state.active.lessonId).hanja}의 현재 진행 대신 ${l.hanja} 공부를 시작해요. 이미 끝낸 문제와 쓰기 기록은 남아요.</p><button class="primary" data-start="${id}">새 글자 시작하기</button><button class="secondary" data-action="resume">하던 공부 이어하기</button>`);return;}openModal(`${l.hanja} · ${l.meaning}`,`<div class="notice">${state.completed[id]?'이미 맞춘 퍼즐 조각이에요. 다시 공부할 수 있어요.':'뜻과 관련된 말을 찾고, 새 어휘의 뜻을 추리해요.'}<br>기본 쓰기는 중간중간 한 번씩, 총 세 번 해요.</div><button class="primary" data-start="${id}">뜻 탐정 시작하기 →</button><button class="secondary" data-practice="${id}">쓰기만 ${state.settings.practice}번 연습하기</button>`);}
function reviewSelection(id){const pool=questions.filter(q=>q.lessonId!==id&&state.records[q.id]);const sorted=[...pool].sort((a,b)=>{const x=state.records[a.id],y=state.records[b.id];return (y.wrong/y.attempts-x.wrong/x.attempts)||x.last-y.last;});return sorted.slice(0,2);}
function start(id){closeModal();const l=lessonById(id);if(!l)return;const steps=[{kind:'question',id:l.questions[0].id},{kind:'writing',pass:1},...l.words.map((_,i)=>({kind:'word',index:i})),{kind:'question',id:l.questions[1].id},{kind:'writing',pass:2},{kind:'question',id:l.questions[2].id},{kind:'question',id:l.questions[3].id},{kind:'writing',pass:3},...reviewSelection(id).map(q=>({kind:'question',id:q.id,review:true}))];state.active={lessonId:id,steps,step:0,results:[],writePasses:0,started:Date.now()};save();showStep();}
function resume(){closeModal();if(state.active)showStep();else home();}
function advance(){if(!state.active)return;state.active.step++;delete state.active.q;delete state.active.strokeIndex;save();if(state.active.step>=state.active.steps.length)complete();else showStep();}
function stageHeader(label){const r=state.active;return `<div class="session-top"><button data-nav="home" aria-label="진행 저장 후 홈으로">← 저장</button><span>${label}</span><span>${r.step+1}/${r.steps.length}</span></div><div class="progress" aria-label="학습 진행">${r.steps.map((_,i)=>`<i class="${i<=r.step?'done':''}"></i>`).join('')}</div>`;}
function showStep(){view='learn';const r=state.active;if(r&&r.step>=r.steps.length){complete();return;}if(!r||!lessonById(r.lessonId)||!r.steps[r.step]){home();return;}const step=r.steps[r.step],l=lessonById(r.lessonId);if(step.kind==='writing'){showWriting(l.hanja,step.pass,3,()=>{r.writePasses++;advance();});return;}if(step.kind==='word'){const w=l.words[step.index];render(`<section class="screen">${stageHeader('어휘 단서 '+(step.index+1)+'/'+l.words.length)}<div class="sheet word-sheet"><span class="eyebrow">WORD CLUE · 말 속 한자 찾기</span><div class="word-display"><strong>${w.word}</strong><small>${w.hanja}</small></div><p class="word-copy">${w.meaning}</p><p class="context">${w.example}</p><p class="tiny muted">${l.hanja}의 뜻 ‘${l.core}’와 연결해 봐요.</p><button class="primary push wide" data-action="advance">읽었어요 · 다음 단서 →</button></div></section>`);return;}showQuestion();}
function currentQuestion(){return questions.find(q=>q.id===state.active?.steps[state.active.step]?.id);}
function showQuestion(){const r=state.active,q=currentQuestion();if(!q){home();return;}if(!r.q){r.q={choices:shuffle(q.choices),tries:0,hint:0,wrong:[],answered:false};save();}const s=r.q,labels={key:'뜻 발견',family:'어휘 연결',inference:'뜻 추리',context:'문맥 조사'};render(`<section class="screen">${stageHeader(r.steps[r.step].review?'누적복습':labels[q.type])}<div class="sheet question-sheet"><div class="row spread"><span class="eyebrow">${lessonById(q.lessonId).hanja} · ${labels[q.type]}</span><button class="text-button" data-action="hint">💡 힌트 ${s.hint}/${q.hints.length}</button></div><h2>${q.title}</h2><div class="context">${q.context}</div><div class="answers">${s.choices.map((c,i)=>`<button class="answer ${s.wrong.includes(i)?'wrong':''} ${s.answered&&c===q.answer?'correct':''}" data-answer="${i}" ${s.answered||s.wrong.includes(i)?'disabled':''}><span>${i+1}</span>${c}</button>`).join('')}</div>${s.answered?'<button class="primary wide" data-action="advance">다음 단서 →</button>':''}</div></section>`);}
function hint(){const r=state.active,q=currentQuestion();if(!q||!r.q)return;r.q.hint=Math.min(q.hints.length,r.q.hint+1);save();showQuestion();openModal('단서를 살펴봐요',`<p class="dialog-body-text">${q.hints[r.q.hint-1]}</p><button class="primary" data-action="close">다시 생각해 볼게요</button>`);}
function answer(index){const r=state.active,q=currentQuestion();if(!q||r.q.answered||r.q.wrong.includes(index))return;const s=r.q,correct=s.choices[index]===q.answer;s.tries++;if(s.tries===1){const rec=state.records[q.id]||{attempts:0,correct:0,wrong:0,hints:0,last:0};rec.attempts++;rec.correct+=Number(correct);rec.wrong+=Number(!correct);rec.last=Date.now();state.records[q.id]=rec;}if(!correct){s.wrong.push(index);save();hint();return;}s.answered=true;state.records[q.id].hints+=Number(s.hint>0);r.results.push({id:q.id,first:s.tries===1,hints:s.hint,review:!!r.steps[r.step].review});save();showQuestion();openModal('단서를 풀었어요! ✓',`<p class="dialog-body-text">${q.explanation}</p><button class="primary" data-action="answer-next">알겠어요 · 다음으로 →</button>`);}
function complete(){const r=state.active;if(!r)return;if(r.writePasses<3||r.results.length!==r.steps.filter(s=>s.kind==='question').length){toast('남은 학습과 쓰기를 마치면 조각이 채워져요.');return;}const first=!state.completed[r.lessonId];state.completed[r.lessonId]={at:Date.now(),count:(state.completed[r.lessonId]?.count||0)+1};if(first)state.coins+=30;const record={...r,at:Date.now(),reward:first?30:0};state.sessions.push(record);state.sessions=state.sessions.slice(-100);state.lastResult=record;state.active=null;save();result();}
function result(){view='learn';const r=state.lastResult;if(!r){home();return;}const l=lessonById(r.lessonId),w=WEEKS.find(w=>w.lessons.includes(l.id)),n=doneCount(w);render(`<section class="screen center result-screen"><div class="eyebrow">PUZZLE PIECE FOUND!</div><h1>${n===5?w.id+'주차 퍼즐 완성!':'한 조각을 맞췄어요!'}</h1><div class="badge-large"><strong>${l.hanja}</strong><span>${l.meaning} · 학습 완료</span></div><div class="stats"><div class="stat"><strong>${r.results.filter(x=>x.first).length}/${r.results.length}</strong><small>첫 시도 정답</small></div><div class="stat"><strong>${r.writePasses}회</strong><small>나눠 쓰기 완료</small></div><div class="stat"><strong>${n}/5</strong><small>${w.id}주차 조각</small></div></div><p class="tiny muted">${r.reward?'끝까지 생각한 노력에 +30포인트!':'복습 기록도 차곡차곡 쌓였어요.'}</p><button class="primary wide" data-portal="${l.id}">중국어에서도 만나 볼까? →</button><button class="secondary wide" data-week="${w.id}">내 퍼즐로 돌아가기</button></section>`);}
function portal(id,index=0){portalLesson=id;portalIndex=index;view='learn';const l=lessonById(id),c=l.chinese;const items=[{word:c.character,pinyin:c.pinyin,meaning:l.core},...c.words,{word:c.sentence,pinyin:c.pinyinSentence,meaning:c.translation}],item=items[index];render(`<section class="screen portal-screen"><div class="session-top"><button data-action="result">← 결과</button><span>중국어 통신실 · 선택 학습</span><span>${index+1}/${items.length}</span></div><div class="portal-page"><span class="eyebrow">같은 글자, 새로운 소리</span><strong class="portal-word" lang="zh-CN">${item.word}</strong><p class="pinyin">${item.pinyin}</p><p>${item.meaning}</p><button class="audio-button" data-speak="${esc(item.word)}" aria-label="여성 목소리로 듣기">▶</button><p class="tiny muted">듣고 내 목소리로 따라 말해요.</p></div>${index===items.length-1?`<button class="secondary wide" data-practice="${id}" data-chinese="true">${c.character}도 ${state.settings.practice}번 써 보기</button>`:''}<div class="pager"><button data-portalpage="${index-1}" ${index===0?'disabled':''}>← 이전</button><span>${index+1} / ${items.length}</span>${index<items.length-1?`<button data-portalpage="${index+1}">다음 →</button>`:'<button data-nav="home">마치기 ✓</button>'}</div></section>`);}
function femaleVoice(){if(!window.speechSynthesis)return null;return speechSynthesis.getVoices().find(v=>/^zh([-_]CN)?$/i.test(v.lang)&&/(Xiaoxiao|Xiaoyi|Huihui|Yaoyao|Tingting|晓晓|晓伊|慧慧|瑶瑶|婷婷)/i.test(v.name+' '+v.voiceURI))||null;}
function speak(text){stopAudio();if(FEMALE_AUDIO[text]){audio=new Audio(FEMALE_AUDIO[text]);audio.onerror=()=>toast('음원을 재생하지 못했어요. 다시 눌러 주세요.');audio.play().catch(()=>toast('듣기 버튼을 다시 눌러 주세요.'));return;}const v=femaleVoice();if(!v){openModal('여성 음성 준비가 필요해요',`<p class="dialog-body-text">이 기기에서 확인된 중국어 여성 음성을 찾지 못했어요. 다른 목소리로 바꾸지 않고 듣기를 멈췄어요.</p><p class="notice">기기의 음성 설정에서 중국어 여성 음성을 설치한 뒤 다시 열어 주세요. 모든 기기에서 같은 목소리를 쓰려면 고정 여성 음원이 필요해요.</p><button class="primary" data-action="close">확인</button>`);return;}const u=new SpeechSynthesisUtterance(text);u.voice=v;u.lang=v.lang;u.rate=.8;u.pitch=1;u.onerror=()=>toast('여성 음성을 재생하지 못했어요. 다시 시도해 주세요.');speechSynthesis.speak(u);}
function settings(){const fixed=Object.keys(FEMALE_AUDIO).length>0,voice=femaleVoice();openModal('연습 설정',`<div class="settings-row"><span>추가 쓰기 연습</span><select id="practice-count" aria-label="추가 쓰기 횟수"><option value="3" ${state.settings.practice===3?'selected':''}>3번 쓰기</option><option value="5" ${state.settings.practice===5?'selected':''}>5번 쓰기</option></select></div><p class="tiny muted">본 학습에서는 세 번을 중간중간 나눠 써요.</p><div class="notice"><b>여성 목소리만 사용</b><br>${fixed?'고정 여성 음원 포함':voice?esc(voice.name):'이 기기에 확인된 여성 음성이 없어요.'}</div><button class="secondary" data-action="export">학습 기록 내려받기</button><button class="text-button" data-action="info">저장·획순 안내 보기</button>`);document.getElementById('practice-count').onchange=e=>{state.settings.practice=Number(e.target.value);save();};}
function info(){openModal('사용 안내',`<p class="notice">기록은 현재 기기의 브라우저에 저장돼요. 다른 학생은 별도 브라우저 프로필을 사용해 주세요.<br><br>획순 자료는 중국어 자형 기준으로, 한국 한자 교재와 다를 수 있어요. 획 경로를 따라 쓰는 연습이며 독립 쓰기 실력 채점은 아니에요.</p><p class="tiny muted">Make Me a Hanzi · Arphic Public License<br>출처와 라이선스 전문은 data.js에 포함돼 있어요.</p><button class="primary" data-action="close">확인</button>`);}
function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jindam-learning-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function report(page=0){view='report';reportPage=Math.max(0,Math.min(Math.ceil(HANJA_DATA.length/3)-1,page));const totals=Object.values(state.records).reduce((a,r)=>({attempts:a.attempts+r.attempts,correct:a.correct+r.correct}),{attempts:0,correct:0});render(`<section class="screen"><span class="eyebrow">COACHING NOTE</span><h1>차곡차곡 학습 기록</h1><div class="stats"><div class="stat"><strong>${WEEKS.filter(w=>doneCount(w)===5).length}</strong><small>완료한 주차</small></div><div class="stat"><strong>${Object.keys(state.completed).length}</strong><small>완료한 글자</small></div><div class="stat"><strong>${totals.attempts?Math.round(totals.correct/totals.attempts*100):0}%</strong><small>첫 응답 정답률</small></div></div><div class="report-list">${HANJA_DATA.slice(reportPage*3,reportPage*3+3).map(l=>{const hints=l.questions.reduce((n,q)=>n+(state.records[q.id]?.hints||0),0),wrong=l.questions.reduce((n,q)=>n+(state.records[q.id]?.wrong||0),0);return `<article class="report-item"><strong>${l.hanja}</strong><div><p><b>${l.meaning}</b> · ${state.completed[l.id]?'학습 완료 ✓':'공부 중 / 시작 전'}</p><small>쓰기 ${state.writing[l.hanja]?.completed||0}회 · 첫 오답 ${wrong}회 · 힌트 ${hints}회</small></div></article>`;}).join('')}</div><p class="tiny muted">틀리거나 힌트를 사용한 어휘는 1:1 코칭에서 확인해 주세요.</p><div class="pager"><button data-reportpage="${reportPage-1}" ${reportPage===0?'disabled':''}>← 이전</button><span>${reportPage+1}/${Math.ceil(HANJA_DATA.length/3)}</span><button data-reportpage="${reportPage+1}" ${(reportPage+1)*3>=HANJA_DATA.length?'disabled':''}>다음 →</button></div></section>`);}
function beginPractice(id,chinese=false){closeModal();practice={id,character:chinese?lessonById(id).chinese.character:lessonById(id).hanja,total:state.settings.practice,pass:1,chinese};practiceStep();}
function practiceStep(){const p=practice;if(!p)return;view='learn';showWriting(p.character,p.pass,p.total,()=>{p.pass++;if(p.pass>p.total){const id=p.id,cn=p.chinese;practice=null;toast('추가 쓰기를 모두 마쳤어요!');if(cn)portal(id,portalIndex);else home();}else practiceStep();},true);}
function stopWriting(){if(writing){cancelAnimationFrame(writing.frame);writing=null;}}
function sampleLine(points,n=32){const lengths=[0];for(let i=1;i<points.length;i++)lengths.push(lengths[i-1]+Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]));const total=lengths.at(-1);if(!total)return Array.from({length:n},()=>points[0]);return Array.from({length:n},(_,i)=>{const target=total*i/(n-1);let j=1;while(j<lengths.length-1&&lengths[j]<target)j++;const t=(target-lengths[j-1])/(lengths[j]-lengths[j-1]||1);return points[j-1].map((x,k)=>x+(points[j][k]-x)*t);});}
function matchesStroke(points,median){if(points.length<3)return false;const length=ps=>ps.slice(1).reduce((sum,p,i)=>sum+Math.hypot(p[0]-ps[i][0],p[1]-ps[i][1]),0),ratio=length(points)/length(median);if(ratio<.55||ratio>1.9)return false;const first=points[0],last=points.at(-1),start=median[0],end=median.at(-1);if((last[0]-first[0])*(end[0]-start[0])+(last[1]-first[1])*(end[1]-start[1])<=0)return false;const a=sampleLine(points),b=sampleLine(median),d=a.map((p,i)=>Math.hypot(p[0]-b[i][0],p[1]-b[i][1]));return d[0]<105&&d.at(-1)<115&&Math.max(...d)<165&&d.reduce((x,y)=>x+y,0)/d.length<85;}
function showWriting(character,pass,total,onDone,extra=false){const data=STROKE_DATA[character];if(!data){toast('이 글자의 획 자료가 필요해요.');return;}const index=extra?0:(state.active.strokeIndex||0);render(`<section class="screen writing-screen">${extra?'<div class="session-top"><button data-nav="home">← 돌아가기</button><span>추가 쓰기 연습</span></div>':stageHeader('글자 단서 기록')}<div class="row spread"><h2>${character} · ${pass}번째 쓰기</h2><span class="pill">${pass>=3?'안내 줄이기':'따라 쓰기'}</span></div><div class="writing-stage">${Array.from({length:total},(_,i)=>`<i class="${i<pass-1?'done':''}">${i<pass-1?'✓':i+1}</i>`).join('')}<span>${pass} / ${total}회</span></div><div class="writing-board"><canvas id="writing-canvas" width="1024" height="1024" aria-label="${character} 한 획씩 따라 쓰기"></canvas></div><p id="writing-status" role="status" aria-live="polite"></p><div class="writing-controls"><button class="secondary" id="writing-demo">획 시범 ▶</button><button class="secondary" id="writing-reset">이번 글자 다시</button></div><button class="primary wide" id="writing-next" disabled>끝까지 쓰면 다음으로!</button></section>`);
const canvas=document.getElementById('writing-canvas'),w=writing={character,data,index,points:[],pointer:null,frame:0,demo:false,recorded:index===data.strokes.length,canvas,ctx:canvas.getContext('2d'),pass,extra};const status=document.getElementById('writing-status');
const update=msg=>status.textContent=msg||`${w.index+1}/${data.strokes.length}획 · 주황색 점에서 출발해요.`;
const completed=()=>{update('✓ 한 번 완성했어요!');const b=document.getElementById('writing-next');b.disabled=false;b.textContent=extra&&pass<total?'좋아요 · 한 번 더 쓰기 →':'완성했어요 · 다음 단서 →';document.getElementById('writing-demo').disabled=true;};
const coords=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)/r.width*1024,900-(e.clientY-r.top)/r.height*1024];};
const cancel=()=>{w.pointer=null;w.points=[];drawWriting(w);};
canvas.addEventListener('pointerdown',e=>{if(w.demo||w.index>=data.strokes.length||w.pointer!==null||e.button>0)return;e.preventDefault();w.pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);w.points=[coords(e)];drawWriting(w);});
canvas.addEventListener('pointermove',e=>{if(w.pointer!==e.pointerId)return;e.preventDefault();w.points.push(coords(e));drawWriting(w);});
canvas.addEventListener('pointerup',e=>{if(w.pointer!==e.pointerId)return;w.points.push(coords(e));w.pointer=null;if(matchesStroke(w.points,data.medians[w.index])){w.index++;if(!extra)state.active.strokeIndex=w.index;if(w.index===data.strokes.length){if(!w.recorded){const r=state.writing[character]||{completed:0};r.completed++;r.last=Date.now();state.writing[character]=r;w.recorded=true;}completed();}else update();save();}else update('점에서 시작해 화살표 방향으로 끝까지 써 봐요.');w.points=[];drawWriting(w);});
canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',()=>{if(w.pointer!==null)cancel();});
document.getElementById('writing-reset').onclick=()=>{cancelAnimationFrame(w.frame);w.demo=false;w.index=0;w.pointer=null;w.points=[];if(!extra){state.active.strokeIndex=0;save();}document.getElementById('writing-next').disabled=true;document.getElementById('writing-next').textContent='끝까지 쓰면 다음으로!';document.getElementById('writing-demo').disabled=false;update();drawWriting(w);};
document.getElementById('writing-demo').onclick=()=>{if(w.demo||w.index>=data.strokes.length)return;w.pointer=null;w.points=[];w.demo=true;const pts=sampleLine(data.medians[w.index],80),start=performance.now();const tick=time=>{if(writing!==w)return;const progress=Math.min(1,(time-start)/1400);w.points=pts.slice(0,Math.max(1,Math.ceil(progress*pts.length)));drawWriting(w);if(progress<1)w.frame=requestAnimationFrame(tick);else{w.demo=false;w.points=[];drawWriting(w);}};w.frame=requestAnimationFrame(tick);};
document.getElementById('writing-next').onclick=()=>{if(w.index===data.strokes.length)onDone();};if(index===data.strokes.length)completed();else update();drawWriting(w);}
function drawWriting(w){const c=w.ctx;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,1024,1024);c.strokeStyle='#dedbd2';c.lineWidth=3;c.setLineDash([12,12]);c.beginPath();c.moveTo(512,0);c.lineTo(512,1024);c.moveTo(0,512);c.lineTo(1024,512);c.moveTo(0,0);c.lineTo(1024,1024);c.moveTo(1024,0);c.lineTo(0,1024);c.stroke();c.setLineDash([]);c.setTransform(1,0,0,-1,0,900);w.data.strokes.forEach((path,i)=>{c.fillStyle=i<w.index?'#293655':i===w.index?'#d1dbea':w.pass>=3?'#fffefa':'#edeae2';c.fill(new Path2D(path));});if(w.index<w.data.medians.length){const m=w.data.medians[w.index],a=m[0],b=sampleLine(m)[7];c.strokeStyle='#c68238';c.lineWidth=7;c.lineCap='round';if(w.pass<3||w.demo){c.setLineDash([10,13]);c.beginPath();m.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();c.setLineDash([]);}c.fillStyle='#df8c36';c.beginPath();c.arc(...a,18,0,Math.PI*2);c.fill();const angle=Math.atan2(b[1]-a[1],b[0]-a[0]);c.beginPath();c.moveTo(...b);c.lineTo(b[0]-24*Math.cos(angle-.55),b[1]-24*Math.sin(angle-.55));c.moveTo(...b);c.lineTo(b[0]-24*Math.cos(angle+.55),b[1]-24*Math.sin(angle+.55));c.stroke();}if(w.points.length){c.strokeStyle=w.demo?'#d39228':'#577ba3';c.lineWidth=24;c.lineJoin='round';c.lineCap='round';c.beginPath();w.points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(d.nav){navigate(d.nav);return;}if(d.week){state.week=Number(d.week);save();navigate('home');return;}if(d.weekpage!==undefined){weeks(Number(d.weekpage));return;}if(d.reportpage!==undefined){report(Number(d.reportpage));return;}if(d.lesson){selectLesson(d.lesson);return;}if(d.start){start(d.start);return;}if(d.practice){beginPractice(d.practice,d.chinese==='true');return;}if(d.answer!==undefined){answer(Number(d.answer));return;}if(d.portal){portal(d.portal);return;}if(d.portalpage!==undefined){portal(portalLesson,Number(d.portalpage));return;}if(d.speak){speak(d.speak);return;}({close:closeModal,weeks:()=>weeks(),settings,info,resume,advance,hint,result,export:exportData,'answer-next':()=>{closeModal();advance();}}[d.action])?.();});
window.addEventListener('pagehide',()=>{save();stopAudio();});
if(!WEEKS.some(w=>w.id===state.week))state.week=WEEKS[0].id;
home();
